import type { CommunityPost } from '../@types';

export const communityPost: CommunityPost[] = [
  {
    id: "p1",
    userId: "u1",
    userName: "Arjun Mehta",
    userAvatar: "https://i.pravatar.cc/150?img=11",
    category: "Coin",
    image: "/vintage_silver_coin.png",
    caption: "Found this 1907 British India One Rupee at a local market today. The detailing is still beautiful.",
    likesCount: 124,
    commentsCount: 18,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-16T10:30:00Z",
    relatedItemId: "m1",
  },
  {
    id: "p2",
    userId: "u2",
    userName: "Priya Sharma",
    userAvatar: "https://i.pravatar.cc/150?img=5",
    category: "BankNote",
    image: "/vintage_banknote.png",
    caption: "Just added this mint condition 10 Rupee Gandhi Centenary note to my collection! So thrilled.",
    likesCount: 342,
    commentsCount: 45,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-15T14:20:00Z",
    relatedItemId: "m2",
  },
  {
    id: "p3",
    userId: "u3",
    userName: "Rahul Verma",
    userAvatar: "https://i.pravatar.cc/150?img=12",
    category: "Set",
    image: "/coin_set_display.png",
    caption: "The 1947 Indian Independence Commemorative Set. A piece of history right in my hands.",
    likesCount: 512,
    commentsCount: 67,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-14T09:15:00Z",
    relatedItemId: "m3",
  },
  {
    id: "p4",
    userId: "u4",
    userName: "Sneha Gupta",
    userAvatar: "https://i.pravatar.cc/150?img=24",
    category: "Commemorative",
    image: "/vintage_silver_coin.png",
    caption: "Look at the shine on this 500 Rupee Commemorative Silver Coin! Proof finish is just incredible.",
    likesCount: 289,
    commentsCount: 22,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-13T18:45:00Z",
    relatedItemId: "m4",
  },
  {
    id: "p5",
    userId: "u5",
    userName: "Amit Patel",
    userAvatar: "https://i.pravatar.cc/150?img=33",
    category: "BankNote",
    image: "/vintage_banknote.png",
    caption: "Found an old 100 Rupee Agriculture Banknote hidden in my grandfather's diary. Memories!",
    likesCount: 156,
    commentsCount: 12,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-12T11:10:00Z",
    relatedItemId: "m5",
  },
  {
    id: "p6",
    userId: "u6",
    userName: "Vikram Singh",
    userAvatar: "https://i.pravatar.cc/150?img=52",
    category: "Coin",
    image: "/antique_copper_coin.png",
    caption: "1862 Victoria Empress One Rupee. It's got some wear, but the patina is wonderful.",
    likesCount: 98,
    commentsCount: 8,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-11T16:30:00Z",
    relatedItemId: "m6",
  },
  {
    id: "p7",
    userId: "u7",
    userName: "Neha Desai",
    userAvatar: "https://i.pravatar.cc/150?img=42",
    category: "Set",
    image: "/coin_set_display.png",
    caption: "Unboxing the Republic of India Proof Coin Set from 1970. The original acrylic packaging is still intact!",
    likesCount: 421,
    commentsCount: 34,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-10T20:00:00Z",
    relatedItemId: "m7",
  },
  {
    id: "p8",
    userId: "u8",
    userName: "Rohan Kapoor",
    userAvatar: "https://i.pravatar.cc/150?img=15",
    category: "Silver",
    image: "/vintage_silver_coin.png",
    caption: "Check out the toning on this 1918 George V Half Rupee. Silver coins age so gracefully.",
    likesCount: 187,
    commentsCount: 15,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-09T08:20:00Z",
    relatedItemId: "m8",
  },
  {
    id: "p9",
    userId: "u9",
    userName: "Pooja Reddy",
    userAvatar: "https://i.pravatar.cc/150?img=32",
    category: "Commemorative",
    image: "/antique_copper_coin.png",
    caption: "A humble addition: 50 Paise Commemorative for the RBI Platinum Jubilee. I love collecting these small denominations.",
    likesCount: 112,
    commentsCount: 9,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-08T13:45:00Z",
    relatedItemId: "m9",
  },
  {
    id: "p10",
    userId: "u10",
    userName: "Sanjay Joshi",
    userAvatar: "https://i.pravatar.cc/150?img=59",
    category: "BankNote",
    image: "/vintage_banknote.png",
    caption: "Nostalgia hits hard! Crisp 10 Rupee Peacock Banknote from the 90s. Who else remembers using these?",
    likesCount: 654,
    commentsCount: 89,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-07T19:10:00Z",
    relatedItemId: "m10",
  },
  {
    id: "p11",
    userId: "u11",
    userName: "Manoj Tiwari",
    userAvatar: "https://i.pravatar.cc/150?img=60",
    category: "Coin",
    image: "/vintage_silver_coin.png",
    caption: "Acquired this 1840 East India Company One Rupee. The continuous legend variety is quite fascinating.",
    likesCount: 231,
    commentsCount: 21,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-06T10:05:00Z",
    relatedItemId: "m11",
  },
  {
    id: "p12",
    userId: "u12",
    userName: "Anjali Menon",
    userAvatar: "https://i.pravatar.cc/150?img=43",
    category: "Set",
    image: "/coin_set_display.png",
    caption: "1971 Food for All Commemorative Set. Mint condition. FAO issues are a unique sub-category in numismatics.",
    likesCount: 145,
    commentsCount: 11,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-05T15:25:00Z",
    relatedItemId: "m12",
  },
  {
    id: "p13",
    userId: "u13",
    userName: "Karan Singh",
    userAvatar: "https://i.pravatar.cc/150?img=61",
    category: "Commemorative",
    image: "/vintage_silver_coin.png",
    caption: "2004 100 Rupee Silver Commemorative for India Post. Huge and heavy! A must-have for silver collectors.",
    likesCount: 310,
    commentsCount: 28,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-04T09:40:00Z",
    relatedItemId: "m13",
  },
  {
    id: "p14",
    userId: "u14",
    userName: "Divya R",
    userAvatar: "https://i.pravatar.cc/150?img=47",
    category: "BankNote",
    image: "/vintage_banknote.png",
    caption: "A piece of recent history: 1000 Rupee Note - 2000 Series. Demonetization feels like yesterday.",
    likesCount: 476,
    commentsCount: 65,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-03T17:15:00Z",
    relatedItemId: "m14",
  },
  {
    id: "p15",
    userId: "u15",
    userName: "Gaurav Das",
    userAvatar: "https://i.pravatar.cc/150?img=53",
    category: "Coin",
    image: "/antique_copper_coin.png",
    caption: "1950 First Republic of India Pice. Bronze coins have a very distinct feel compared to modern alloys.",
    likesCount: 132,
    commentsCount: 14,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-02T12:50:00Z",
    relatedItemId: "m15",
  },
  {
    id: "p16",
    userId: "u16",
    userName: "Meera Nair",
    userAvatar: "https://i.pravatar.cc/150?img=34",
    category: "Commemorative",
    image: "/vintage_silver_coin.png",
    caption: "1997 Subhash Chandra Bose Commemorative 2 Rupee coin. A tribute to a great leader.",
    likesCount: 267,
    commentsCount: 19,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-07-01T08:35:00Z",
    relatedItemId: "m16",
  },
  {
    id: "p17",
    userId: "u17",
    userName: "Rakesh Kumar",
    userAvatar: "https://i.pravatar.cc/150?img=14",
    category: "BankNote",
    image: "/vintage_banknote.png",
    caption: "The majestic Bengal Tiger on this 2 Rupee Banknote. Iconic design from the past.",
    likesCount: 389,
    commentsCount: 42,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-06-30T21:00:00Z",
    relatedItemId: "m17",
  },
  {
    id: "p18",
    userId: "u18",
    userName: "Anil Sethi",
    userAvatar: "https://i.pravatar.cc/150?img=68",
    category: "Silver",
    image: "/vintage_silver_coin.png",
    caption: "1885 Victoria Silver Rupee. Found this in an estate sale. The mint mark is perfectly clear.",
    likesCount: 245,
    commentsCount: 26,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-06-29T14:10:00Z",
    relatedItemId: "m18",
  },
  {
    id: "p19",
    userId: "u19",
    userName: "Sonali Jain",
    userAvatar: "https://i.pravatar.cc/150?img=49",
    category: "Set",
    image: "/coin_set_display.png",
    caption: "1974 Planned Families Coin Set. Such interesting themes were chosen for early commemorative sets.",
    likesCount: 178,
    commentsCount: 16,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-06-28T10:45:00Z",
    relatedItemId: "m19",
  },
  {
    id: "p20",
    userId: "u20",
    userName: "Deepak Chahar",
    userAvatar: "https://i.pravatar.cc/150?img=51",
    category: "Commemorative",
    image: "/vintage_silver_coin.png",
    caption: "2010 Commonwealth Games 100 Rs Commemorative. Hard to believe this event was over 15 years ago!",
    likesCount: 512,
    commentsCount: 54,
    isLiked: false,
    isSaved: false,
    createdAt: "2026-06-27T16:20:00Z",
    relatedItemId: "m20",
  }
];