import type { MarketPlaceItem } from '../@types';

export const marketplaceItems: MarketPlaceItem[] = [
  {
    id: "m1",
    title: "1907 British India One Rupee",
    category: "Coin",
    condition: "Excellent",
    price: 3200,
    currency: "INR",
    sellerName: "Arjun Mehta",
    sellerAvatar: "https://i.pravatar.cc/150?img=11",
    location: "Bengaluru, Karnataka",
    image: "/vintage_silver_coin.png",
    gallery: [
      "/vintage_silver_coin.png",
      "/antique_copper_coin.png"
    ],
    description: "Silver coin in collectible condition with visible details and light wear.",
    tags: ["rare", "silver", "india"],
    datePosted: "2026-07-10",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m2",
    title: "10 Rupee Gandhi Centenary Banknote",
    category: "BankNote",
    condition: "Mint",
    price: 1500,
    currency: "INR",
    sellerName: "Priya Sharma",
    sellerAvatar: "https://i.pravatar.cc/150?img=5",
    location: "Mumbai, Maharashtra",
    image: "/vintage_banknote.png",
    gallery: [
      "/vintage_banknote.png"
    ],
    description: "Uncirculated 10 Rupee note commemorating Mahatma Gandhi's centenary.",
    tags: ["banknote", "gandhi", "mint"],
    datePosted: "2026-07-12",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m3",
    title: "1947 Indian Independence Commemorative Set",
    category: "Set",
    condition: "Excellent",
    price: 12500,
    currency: "INR",
    sellerName: "Rahul Verma",
    sellerAvatar: "https://i.pravatar.cc/150?img=12",
    location: "New Delhi, Delhi",
    image: "/coin_set_display.png",
    description: "Complete set of coins issued in 1947 to mark India's independence.",
    tags: ["set", "independence", "historic"],
    datePosted: "2026-07-14",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m4",
    title: "500 Rupee Commemorative Silver Coin",
    category: "Commemorative",
    condition: "Mint",
    price: 8500,
    currency: "INR",
    sellerName: "Sneha Gupta",
    sellerAvatar: "https://i.pravatar.cc/150?img=24",
    location: "Kolkata, West Bengal",
    image: "/vintage_silver_coin.png",
    description: "Pure silver commemorative coin in original presentation box.",
    tags: ["silver", "commemorative", "proof"],
    datePosted: "2026-07-15",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m5",
    title: "Vintage 100 Rupee Agriculture Banknote",
    category: "BankNote",
    condition: "Good",
    price: 800,
    currency: "INR",
    sellerName: "Amit Patel",
    sellerAvatar: "https://i.pravatar.cc/150?img=33",
    location: "Ahmedabad, Gujarat",
    image: "/vintage_banknote.png",
    description: "Old 100 Rupee note featuring agricultural motifs. Some folds visible.",
    tags: ["banknote", "vintage", "agriculture"],
    datePosted: "2026-07-11",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m6",
    title: "1862 Victoria Empress One Rupee",
    category: "Coin",
    condition: "Fair",
    price: 1800,
    currency: "INR",
    sellerName: "Vikram Singh",
    sellerAvatar: "https://i.pravatar.cc/150?img=52",
    location: "Jaipur, Rajasthan",
    image: "/antique_copper_coin.png",
    description: "1862 Victoria Rupee, significant wear but date and main features legible.",
    tags: ["victoria", "silver", "antique"],
    datePosted: "2026-07-08",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m7",
    title: "Republic of India Proof Coin Set 1970",
    category: "Set",
    condition: "Mint",
    price: 15000,
    currency: "INR",
    sellerName: "Neha Desai",
    sellerAvatar: "https://i.pravatar.cc/150?img=42",
    location: "Pune, Maharashtra",
    image: "/coin_set_display.png",
    description: "1970 proof set in original acrylic packaging. Flawless condition.",
    tags: ["proof", "set", "republic"],
    datePosted: "2026-07-16",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m8",
    title: "1918 George V Half Rupee",
    category: "Silver",
    condition: "Excellent",
    price: 2400,
    currency: "INR",
    sellerName: "Rohan Kapoor",
    sellerAvatar: "https://i.pravatar.cc/150?img=15",
    location: "Chandigarh",
    image: "/vintage_silver_coin.png",
    description: "Beautifully toned half rupee from 1918.",
    tags: ["georgev", "halfrupee", "silver"],
    datePosted: "2026-07-13",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m9",
    title: "50 Paise Commemorative - RBI Platinum Jubilee",
    category: "Commemorative",
    condition: "Excellent",
    price: 300,
    currency: "INR",
    sellerName: "Pooja Reddy",
    sellerAvatar: "https://i.pravatar.cc/150?img=32",
    location: "Hyderabad, Telangana",
    image: "/antique_copper_coin.png",
    description: "Stainless steel commemorative coin for RBI Platinum Jubilee.",
    tags: ["rbi", "50paise", "commemorative"],
    datePosted: "2026-07-17",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m10",
    title: "10 Rupee Peacock Banknote 1990s",
    category: "BankNote",
    condition: "Mint",
    price: 450,
    currency: "INR",
    sellerName: "Sanjay Joshi",
    sellerAvatar: "https://i.pravatar.cc/150?img=59",
    location: "Nagpur, Maharashtra",
    image: "/vintage_banknote.png",
    description: "Crisp uncirculated 10 rupee note with peacock reverse.",
    tags: ["peacock", "mint", "banknote"],
    datePosted: "2026-07-09",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m11",
    title: "1840 East India Company One Rupee",
    category: "Coin",
    condition: "Good",
    price: 4500,
    currency: "INR",
    sellerName: "Manoj Tiwari",
    sellerAvatar: "https://i.pravatar.cc/150?img=60",
    location: "Lucknow, UP",
    image: "/vintage_silver_coin.png",
    description: "East India Company era continuous legend silver rupee.",
    tags: ["eic", "silver", "antique"],
    datePosted: "2026-07-05",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m12",
    title: "1971 Food for All Commemorative Set",
    category: "Set",
    condition: "Mint",
    price: 3200,
    currency: "INR",
    sellerName: "Anjali Menon",
    sellerAvatar: "https://i.pravatar.cc/150?img=43",
    location: "Kochi, Kerala",
    image: "/coin_set_display.png",
    description: "UNC set of Food for All FAO commemorative coins.",
    tags: ["fao", "foodforall", "set"],
    datePosted: "2026-07-16",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m13",
    title: "2004 100 Rupee Silver Commemorative",
    category: "Commemorative",
    condition: "Excellent",
    price: 5500,
    currency: "INR",
    sellerName: "Karan Singh",
    sellerAvatar: "https://i.pravatar.cc/150?img=61",
    location: "Indore, MP",
    image: "/vintage_silver_coin.png",
    description: "100 Rupee silver coin commemorating India Post.",
    tags: ["silver", "indiapost", "commemorative"],
    datePosted: "2026-07-11",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m14",
    title: "1000 Rupee Note - 2000 Series",
    category: "BankNote",
    condition: "Excellent",
    price: 2500,
    currency: "INR",
    sellerName: "Divya R",
    sellerAvatar: "https://i.pravatar.cc/150?img=47",
    location: "Chennai, Tamil Nadu",
    image: "/vintage_banknote.png",
    description: "Demonetized 1000 rupee note in excellent collector condition.",
    tags: ["demonetized", "1000rupee", "banknote"],
    datePosted: "2026-07-06",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m15",
    title: "1950 First Republic of India Pice",
    category: "Coin",
    condition: "Fair",
    price: 150,
    currency: "INR",
    sellerName: "Gaurav Das",
    sellerAvatar: "https://i.pravatar.cc/150?img=53",
    location: "Guwahati, Assam",
    image: "/antique_copper_coin.png",
    description: "First series bronze pice of the Republic of India.",
    tags: ["republic", "bronze", "pice"],
    datePosted: "2026-07-14",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m16",
    title: "1997 Subhash Chandra Bose Commemorative",
    category: "Commemorative",
    condition: "Good",
    price: 400,
    currency: "INR",
    sellerName: "Meera Nair",
    sellerAvatar: "https://i.pravatar.cc/150?img=34",
    location: "Thiruvananthapuram, Kerala",
    image: "/vintage_silver_coin.png",
    description: "2 Rupee coin marking Netaji Subhash Chandra Bose centenary.",
    tags: ["netaji", "bose", "commemorative"],
    datePosted: "2026-07-02",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m17",
    title: "2 Rupee Tiger Series Banknote",
    category: "BankNote",
    condition: "Excellent",
    price: 250,
    currency: "INR",
    sellerName: "Rakesh Kumar",
    sellerAvatar: "https://i.pravatar.cc/150?img=14",
    location: "Patna, Bihar",
    image: "/vintage_banknote.png",
    description: "Classic 2 rupee note featuring the Bengal Tiger.",
    tags: ["tiger", "2rupee", "banknote"],
    datePosted: "2026-07-12",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m18",
    title: "1885 Victoria Silver Rupee",
    category: "Silver",
    condition: "Good",
    price: 3800,
    currency: "INR",
    sellerName: "Anil Sethi",
    sellerAvatar: "https://i.pravatar.cc/150?img=68",
    location: "Ludhiana, Punjab",
    image: "/vintage_silver_coin.png",
    description: "Victoria Empress silver rupee with clear mint mark.",
    tags: ["victoria", "silver", "1885"],
    datePosted: "2026-07-10",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m19",
    title: "1974 Planned Families Coin Set",
    category: "Set",
    condition: "Excellent",
    price: 2800,
    currency: "INR",
    sellerName: "Sonali Jain",
    sellerAvatar: "https://i.pravatar.cc/150?img=49",
    location: "Surat, Gujarat",
    image: "/coin_set_display.png",
    description: "Planned Families, Food for All uncirculated set.",
    tags: ["plannedfamilies", "set", "unc"],
    datePosted: "2026-07-16",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  },
  {
    id: "m20",
    title: "2010 Commonwealth Games 100 Rs Commemorative",
    category: "Commemorative",
    condition: "Mint",
    price: 4200,
    currency: "INR",
    sellerName: "Deepak Chahar",
    sellerAvatar: "https://i.pravatar.cc/150?img=51",
    location: "Noida, UP",
    image: "/vintage_silver_coin.png",
    description: "100 Rupee uncirculated coin for Delhi Commonwealth Games.",
    tags: ["cwg", "100rupee", "commemorative"],
    datePosted: "2026-07-17",
    isWishlisted: false,
    isInCollection: false,
    isSelling: false,
  }
];